### ISSUE TITLE
Conversion between struct and json

### ISSUE THREAD

**Issue by jrmy1** [purdueapp/PurdueWashServer#1]
It is very difficult to convert our struct room into a json for the server. Consider just using maps for easier conversion? or parse struct in string form?

**Comment by tobiola** [comment]
Yeah man this is a hard bug. We should consider just using structs but finding a good standard way of doing this.

**Comment by jrmy1** [comment]
You bring up a good point. I suggest looking more into the ` operator next to the struct property.

**Comment by jrmy1** [comment]
use `json: "name"` after struct property. struct property must be uppercase.
